### ISSUE TITLE
Make installation instructions more prominent in documentation

### ISSUE THREAD

**Issue by gregelin** [GovReady/CUB#3]
@woodt: I tried to run sample line from `sample-pipeline.sh` and encountered error:

```
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
```

Searched on line and found helpful issue: https://github.com/explosion/spaCy/issues/4577.

Ran command, `python -m spacy download en_core_web_sm` and had progress, but encountered this issue:

```
$ python ssp.py --reader json-l match --components data/ssp-components.json data/ssps/ssp1.jsonl
Traceback (most recent call last):
  File "ssp.py", line 461, in <module>
    cli()
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "ssp.py", line 422, in match
    nlp.add_pipe(ruler, before="ner")
  File "/codedata/code/CUB/venv/lib/python3.8/site-packages/spacy/language.py", line 748, in add_pipe
    raise ValueError(err)
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <spacy.pipeline.entityruler.EntityRuler object at 0x112964400> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.
```

**Comment by gregelin** [comment]
As per @woodt, it is critical to install `en_core_web_sm` as specified in `README.md`:

`python -m spacy download en_core_web_sm`

**Comment by woodt** [comment]
Yes, per the README you need to install the specified requirements and download the spacy language model(s).  I think the wrong version of spacy was installed.

Both of these issues are addressed in the README, which suggests that moving the installation instructions closer to the start of the file would be useful.

I'd like to consider the poetry configuration the source of truth for dependency.  Ideally, we would drop the pip requirements files, but a reasonable alternative would be to generate a pip requirements.txt file from the poetry.lock file.

**Comment by woodt** [comment]
So ... I'd like to rename this issue to "Make installation instructions more prominent in docs", and create another issue to deal with the requirements file situation.

**Comment by gregelin** [comment]
Sure...

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

**Comment by woodt** [comment]
Completed, apparently!
